AllCops:
  TargetRubyVersion: 2.6.6
  NewCops: enable
  Include:
    - '**/*.rb'
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'vendor/bundle/**/*'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'